-- 1. 创建完整的角色表 (包含基础字段和刚设计的详情字段)
CREATE TABLE character_info (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR2(50) NOT NULL,
                                image VARCHAR2(255),
                                rarity NUMBER,
                                element VARCHAR2(50),
                                weapon_type VARCHAR2(50),
                                backstory CLOB,
                                skills CLOB,
                                build_guide CLOB
);

-- 2. 添加表注释和字段注释
COMMENT ON TABLE character_info IS '鸣潮角色信息表';
COMMENT ON COLUMN character_info.name IS '角色名称';
COMMENT ON COLUMN character_info.rarity IS '星级';
COMMENT ON COLUMN character_info.element IS '属性';
COMMENT ON COLUMN character_info.weapon_type IS '武器类型';
COMMENT ON COLUMN character_info.backstory IS '背景故事';
COMMENT ON COLUMN character_info.skills IS '技能信息 (JSON格式)';
COMMENT ON COLUMN character_info.build_guide IS '养成建议';

-- 3. 插入 ID 为 1 的安可完整数据
INSERT INTO character_info (
    id, name, image, rarity, element, weapon_type, backstory, skills, build_guide
) VALUES (
             1,
             '安可',
             '/images/anke.png',
             5,
             '热熔',
             '法器',
             '来自索拉里斯的神秘共鸣者，拥有操控衍射之力的天赋。曾在一次意外中觉醒了强大的共鸣能力，从此踏上了探索世界真相的旅途。',
             '[{"name":"共鸣技能","desc":"释放衍射能量，对前方敌人造成大量伤害"},{"name":"共鸣解放","desc":"进入强化状态，大幅提升攻击力和暴击率，持续15秒"},{"name":"变奏技能","desc":"切换角色时释放能量波动，对周围敌人造成范围伤害"},{"name":"延奏技能","desc":"角色退场后留下能量场，持续对范围内敌人造成伤害"}]',
             '推荐武器：千古潆流（5星长刃）' || CHR(10) || '推荐声骸套装：沉日劫明 4件套' || CHR(10) || '主词条优先级：暴击率 > 暴击伤害 > 攻击力'
         );

-- 4. 提交事务保存数据
COMMIT;